[package]
edition = "2021"
description = "Ethcore stratum lib"
name = "ethcore-stratum"
version = "1.12.0"
license = "GPL-3.0"
authors = ["Parity Technologies <admin@parity.io>"]

[dependencies]
ethereum-types = "0.9.2"
keccak-hash = "0.5.1"
jsonrpc-core = "15.0.0"
jsonrpc-tcp-server = "15.0.0"
log = "0.4"
parking_lot = "0.12.4"

[dev-dependencies]
env_logger = "0.5"
tokio = { version = "1.46.1", features = ["net", "io-util", "rt", "time"] }
