[target.aarch64-apple-darwin]
rustflags = [
	"-L/opt/homebrew/opt/lz4/lib",
	"-L/opt/homebrew/opt/zstd/lib",
	"-L/opt/homebrew/opt/snapp/lib",
	"-L/opt/homebrew/opt/rocksdb/lib",
	"-Clink-arg=-lbz2",
	"-Clink-arg=-llz4",
	"-Clink-arg=-lzstd",
	"-Clink-arg=-lz",
	"-Ctarget-feature=+aes",
]

[target.x86_64-unknown-linux-gnu]
rustflags = [
	"-Clink-arg=-s",
	"-Ctarget-feature=+aes",
	"-Ctarget-feature=+ssse3",
]
rustdocflags = [
	"-Clink-arg=-s",
	"-Ctarget-feature=+aes",
	"-Ctarget-feature=+ssse3",
]
