[target.x86_64-apple-darwin]
rustflags = [
	"-L/usr/local/opt/snappy/lib",
	"-L/usr/local/opt/rocksdb/lib",
	"-Ctarget-feature=+aes"
]

[target.aarch64-apple-darwin]
rustflags = [
	"-L/usr/local/opt/bzip2/lib",
	"-L/usr/local/opt/lz4/lib",
	"-L/usr/local/opt/zstd/lib",
	"-L/usr/local/opt/snappy/lib",
	"-L/usr/local/opt/rocksdb/lib",
	"-Clink-arg=-lbz2",
	"-Clink-arg=-llz4",
	"-Clink-arg=-lzstd",
	"-Clink-arg=-lz",
	"-Ctarget-feature=+aes"
]
