[source.crates-io]
replace-with = "vendored-sources"

# [source."git+https://github.com/gnosis/reth.git?rev=573e128"]
# git = "https://github.com/gnosis/reth.git"
# rev = "573e128"
# replace-with = "vendored-sources"

# [source."git+https://github.com/matter-labs/eip1962.git?rev=ece6cbabc41948db4200e41f0bfdab7ab94c7af8"]
# git = "https://github.com/matter-labs/eip1962.git"
# rev = "ece6cbabc41948db4200e41f0bfdab7ab94c7af8"
# replace-with = "vendored-sources"

# [source."git+https://github.com/openethereum/app-dirs-rs"]
# git = "https://github.com/openethereum/app-dirs-rs"
# replace-with = "vendored-sources"

# [source."git+https://github.com/paritytech/rust-ctrlc.git"]
# git = "https://github.com/paritytech/rust-ctrlc.git"
# replace-with = "vendored-sources"

# [source."git+https://github.com/paritytech/rust-secp256k1?rev=9791e79f21a5309dcb6e0bd254b1ef88fca2f1f4"]
# git = "https://github.com/paritytech/rust-secp256k1"
# rev = "9791e79f21a5309dcb6e0bd254b1ef88fca2f1f4"
# replace-with = "vendored-sources"

# [source."git+https://github.com/rimrakhimov/ethabi?branch=rimrakhimov/remove-syn-export-span"]
# git = "https://github.com/rimrakhimov/ethabi"
# branch = "rimrakhimov/remove-syn-export-span"
# replace-with = "vendored-sources"

[source.vendored-sources]
directory = "vendor"
