[package]
edition = "2021"
description = "Parity Ethereum Logger Implementation"
name = "ethcore-logger"
version = "1.12.0"
license = "GPL-3.0"
authors = ["Parity Technologies <admin@parity.io>"]

[dependencies]
log = "0.4"
env_logger = "0.5"
atty = "0.2.14"
lazy_static = "1.5.0"
regex = "1.11.1"
time = "0.2.23"
chrono = "0.4.38"
parking_lot = "0.12.4"
arrayvec = "0.4"
ansi_term = "0.12.1"
