[parity]
chain = "BASE_DIRECTORYchain/spec.json"
base_path = "BASE_DIRECTORYdata"
no_persistent_txqueue = true

[network]
min_peers = 2
max_peers = 10
reserved_peers = "BASE_DIRECTORYchain/reserved_peers"
port = 30304
reserved_only = true
warp = false

[rpc]
interface = "0.0.0.0"
port = 8546
cors = ["all"]
hosts = ["none"]
apis = ["web3", "eth", "net", "rpc", "parity"]

[ipc]
disable = true

[websockets]
disable = true

[secretstore]
disable = true

[misc]
json = true
logging = "network=info,miner=info,own_tx=info,external_tx=info,poa=info,chain=info,discovery=info,network=info,local_store=info,txqueue=info"
log_file = "BASE_DIRECTORYdata/logs"

[account]
password = ["BASE_DIRECTORYpassword"]

[mining]
reseal_on_txs = "none"
engine_signer = ""
force_sealing = true
gas_floor_target = "40000000"



