[package]
edition = "2015"
description = "Mock fetcher for testing"
name = "fake-fetch"
version = "0.0.1"
license = "GPL-3.0"
authors = ["Parity Technologies <admin@parity.io>"]

[dependencies]
fetch = { path = "../fetch" }
futures = "0.1"
hyper = "1.5"
