name: Docker Image Latest

on:
  push:
    branches: ["main"]

jobs:
  deploy-docker:
    name: Build Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Deploy to docker hub
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: ihkmuenchen/openethereum
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          dockerfile: Dockerfile
          tags: "latest"
