name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    name: Build Latest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag ihkmuenchen/openethereum:$(date +%s)
